<template>
  <v-container>

    <v-row align="center" justify="space-between" class="mb-4 header-row">
      <v-col cols="auto">
        <h1 class="title">Invoice List</h1>
      </v-col>

      <v-col cols="auto" class="d-flex align-center">
       
        <v-text-field
          v-model="search"
          label="Search"
          outlined
          dense
          prepend-inner-icon="mdi-magnify"
          class="search-bar"
        ></v-text-field>
      </v-col>
    </v-row>

   
    <v-row no-gutters>
      <v-col cols="4" v-for="(card, index) in summaryCards" :key="card.title">
        <v-card
          :class="['summary-card', { 'selected-card': selectedCardIndex === index }]"
          @click="selectCard(index)"
          class="pa-2"
        >
          <v-card-title class="text-center">{{ card.title }}</v-card-title>
          <v-card-text class="stat-text">{{ card.value }}</v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Filter & Actions Row -->
    <v-row class="mb-4" align="center" justify="space-between">
      <v-col cols="6">
        <v-select
          v-model="selectedFilter"
          :items="filterOptions"
          item-title="text"
          item-value="value"
          label="Generated By Filter"
          dense
          outlined
          class="filter-select"
        ></v-select>
      </v-col>
      <v-col cols="auto">
        <!-- Create Invoice Button -->
        <v-btn color="primary" @click="createInvoice">Create Invoice</v-btn>
      </v-col>
    </v-row>

    <!-- Table Description -->
    <v-row class="mb-2">
      <v-col cols="12">
        <v-card class="table-description pa-2">
          <v-row>
            <v-col cols="2"><strong>ID</strong></v-col>
            <v-col cols="2"><strong>Initiated On</strong></v-col>
            <v-col cols="2"><strong>Generated By</strong></v-col>
            <v-col cols="2"><strong>Customer Name</strong></v-col>
          </v-row>
        </v-card>
      </v-col>
    </v-row>

    <!-- Invoice Table -->
    <v-card class="table-card">
      <v-data-table
        :headers="headers"
        :items="filteredInvoices"
        class="custom-table"
        hide-default-footer
      >
        <template v-slot:header="{ header }">
          <th :class="['text-center', 'custom-header']">
            {{ header.text }}
          </th>
        </template>
        <template v-slot:item="{ item }">
          <tr>
            <td class="text-center">{{ item.id }}</td>
            <td class="text-center">{{ item.initiatedOn }}</td>
            <td class="text-center">
              {{ item.generatedBy === 'user' ? 'User' : 'Panel' }}
            </td>
            <td>{{ item.customerName }}</td>
            <td class="text-center">
              <v-btn icon @click="editInvoice(item.id)">
                <v-icon>mdi-pencil</v-icon>
              </v-btn>
            </td>
          </tr>
        </template>
      </v-data-table>
    </v-card>
  </v-container>
</template>

<script>
import { computed, ref } from 'vue';

export default {
  setup() {
    const search = ref('');
    const selectedFilter = ref('total');
    const selectedCardIndex = ref(null);

    const invoices = ref([
      {
        id: 1,
        initiatedOn: '2024-10-27 10:00 AM',
        generatedBy: 'user',
        customerName: 'Resham Pandey (999322200)',
      },
      {
        id: 2,
        initiatedOn: '2024-10-26 11:00 AM',
        generatedBy: 'panel',
        customerName: 'Uday Pandey (9876789765)',
      },
    ]);

    const filterOptions = [
      { text: 'Total', value: 'total' },
      { text: 'User Generated', value: 'user' },
      { text: 'Panel Generated', value: 'panel' },
    ];

    const headers = [
      { text: 'ID', value: 'id' },
      { text: 'Initiated On', value: 'initiatedOn' },
      { text: 'Generated By', value: 'generatedBy' },
      { text: 'Customer Name & Contact', value: 'customerName' },
      { text: 'Actions', value: 'actions', sortable: false },
    ];

    const filteredInvoices = computed(() => {
      let result = invoices.value;
      if (selectedFilter.value !== 'total') {
        result = result.filter(
          (invoice) => invoice.generatedBy === selectedFilter.value
        );
      }
      if (search.value) {
        const term = search.value.toLowerCase();
        result = result.filter((invoice) =>
          invoice.customerName.toLowerCase().includes(term)
        );
      }
      return result;
    });

    const totalInvoices = computed(() => invoices.value.length);
    const userInvoices = computed(() =>
      invoices.value.filter((inv) => inv.generatedBy === 'user').length
    );
    const panelInvoices = computed(() =>
      invoices.value.filter((inv) => inv.generatedBy === 'panel').length
    );

    const summaryCards = computed(() => [
      { title: 'Total Invoices', value: totalInvoices.value },
      { title: 'User Generated', value: userInvoices.value },
      { title: 'Panel Generated', value: panelInvoices.value },
    ]);

    const createInvoice = () => {
      console.log('Create Invoice');
    };

    const editInvoice = (id) => {
      console.log('Edit Invoice', id);
    };

    const selectCard = (index) => {
      selectedCardIndex.value = index;
    };

    return {
      search,
      selectedFilter,
      filterOptions,
      headers,
      filteredInvoices,
      summaryCards,
      createInvoice,
      editInvoice,
      selectCard,
      selectedCardIndex,
    };
  },
};
</script>

<style scoped>

.title {
  font-size: 1.8rem;
  font-weight: bold;
  color: #333;
}

.summary-card {
  padding: 15px;
  text-align: center;
  border-radius: 10px;
  cursor: pointer;
  transition: background-color 0.3s, color 0.3s;
}

.summary-card.selected-card {
  background: linear-gradient(to right, #64b5f6, #2196f3);
  color: white;
}

.stat-text {
  font-size: 1.5rem;
  font-weight: bold;
}

/* Table */
.table-card {
  margin-top: 10px;
  padding: 0;
  border-radius: 10px;
}

.custom-table th,
.custom-table td {
  padding: 8px 0; 
}

.custom-table th {
  background-color: #ADD8E6; 
  text-align: center;
  color: black;
}

.custom-table tr:nth-child(even) {
  background-color: #f9f9f9;
}

.custom-table tr:nth-child(odd) {
  background-color: white;
}

.table-description {
  background-color: #eeeeee;
  border-radius: 10px;
  padding: 5px; 
  margin-bottom: 10px;
}


.filter-button {
  background-color: white;
  border: 1px solid #ccc;
  color: #333;
}


.filter-select >>> .v-input__control {
  width: 150px !important; 
}


.header-row {
  border-bottom: 1px solid #eee; 
  padding-bottom: 10px; 
}


.search-bar {
  width: 200px; 
  max-width: none; 
}
</style>
