<template>
  <v-select
    :model-value="modelValue"
    :items="filterOptions"
    label="Generated by Filter"
    outlined
    @update:model-value="$emit('update:modelValue', $event)"
  ></v-select>
</template>

<script>
export default {
  name: 'FilterDropdown',
  props: {
    modelValue: {
      type: String,
      default: null
    }
  },
  emits: ['update:modelValue'],
  data() {
    return {
      filterOptions: [
        { text: 'All', value: null },
        { text: 'User Generated', value: 'user' },
        { text: 'Panel Generated', value: 'panel' },
      ],
    };
  },
};
</script>

<style scoped>
/* Add custom styles here */
</style>