<template>
  <v-data-table
    :headers="headers"
    :items="invoices"
    class="elevation-1"
  >
    <template v-slot:[`item.actions`]="{ item }">
      <v-btn color="primary" @click="editInvoice(item)">Edit</v-btn>
    </template>
  </v-data-table>
</template>

<script>
export default {
  name: 'InvoiceTable',
  props: {
    invoices: {
      type: Array,
      required: true,
    },
  },
  emits: ['edit'],
  data() {
    return {
      headers: [
        { text: 'ID', value: 'id' },
        { text: 'Initiated On', value: 'initiatedOn' },
        { text: 'Generated By', value: 'generatedBy' },
        { text: 'Customer Name', value: 'customerName' },
        { text: 'Actions', value: 'actions', sortable: false },
      ],
    };
  },
  methods: {
    editInvoice(item) {
      this.$emit('edit', item)
    },
  },
};
</script>

<style scoped>

</style>